###Mount Google Drive

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
%cd '/content/gdrive/MyDrive/CS224R/Project/MaterialsProject/'
!pwd
!ls -al

/content/gdrive/MyDrive/CS224R/Project/MaterialsProject
/content/gdrive/MyDrive/CS224R/Project/MaterialsProject
total 1772
-rw------- 1 root root 912569 May 19 13:28 Adsorbate_starOH2_v2.csv
-rw------- 1 root root 393136 May 20 20:47 get_materials_project_data.ipynb
-rw------- 1 root root 127874 May 20 14:46 id_elements.csv
-rw------- 1 root root    173 May 20 20:45 starOH2_lowest_energy5-20-23.gsheet
-rw------- 1 root root 379470 May 20 20:48 starOH2_lowest_energy5-20-23v2.csv


#### Process the unique element catalyst file

In [ ]:
import csv
import numpy as np

filename = "starOH2_lowest_energy5-20-23v2.csv"
starOH2element = []

with open(filename, 'r') as data:
  for line in csv.DictReader(data):
    starOH2element.append(line)

In [ ]:
print("number of catalysts in starOHelement: ", len(starOH2element))
print("sample of data: ", starOH2element[0])
print("sample of data: ", starOH2element[2300]["Bulk_Formula"])    

number of catalysts in starOHelement:  2379
sample of data:  {'ix': '1', 'Element combo': 'Ag||', 'material_id': 'mp-124', 'El0': 'Ag', 'El1': '', 'El2': '', 'Bulk_Formula': 'Ag', 'Energy': '-0.092', 'Ag': '1', 'Al': '0', 'As': '0', 'Au': '0', 'B': '0', 'Bi': '0', 'C': '0', 'Ca': '0', 'Cd': '0', 'Cl': '0', 'Co': '0', 'Cr': '0', 'Cs': '0', 'Cu': '0', 'Fe': '0', 'Ga': '0', 'Ge': '0', 'H': '0', 'Hf': '0', 'Hg': '0', 'In': '0', 'Ir': '0', 'K': '0', 'Mn': '0', 'Mo': '0', 'N': '0', 'Na': '0', 'Nb': '0', 'Ni': '0', 'Os': '0', 'P': '0', 'Pb': '0', 'Pd': '0', 'Pt': '0', 'Rb': '0', 'Re': '0', 'Rh': '0', 'Ru': '0', 'S': '0', 'Sb': '0', 'Sc': '0', 'Se': '0', 'Si': '0', 'Sn': '0', 'Sr': '0', 'Ta': '0', 'Tc': '0', 'Te': '0', 'Ti': '0', 'Tl': '0', 'V': '0', 'W': '0', 'Y': '0', 'Zn': '0', 'Zr': '0', 'Sum': '1', 'Count': '0', '': '0'}
sample of data:  ZrSc


#### Create the numpy matrix of states

In [ ]:
ns = len(starOH2element)
elems = [
    'Ag', 'Al',	'As', 'Au', 'B', 'Bi', 'C', 'Ca', 'Cd', 'Cl', 'Co', 'Cr', 'Cs', 'Cu', 'Fe', 'Ga', 'Ge', 'H', 'Hf', 'Hg', 'In', 'Ir', 'K', 'Mn', 'Mo', 'N', 'Na', 'Nb', 'Ni', 'Os', 'P', 'Pb', 'Pd', 'Pt', 'Rb', 'Re', 'Rh', 'Ru', 'S', 'Sb', 'Sc', 'Se', 'Si', 'Sn', 'Sr', 'Ta', 'Tc', 'Te', 'Ti', 'Tl', 'V', 'W', 'Y', 'Zn', 'Zr'
    ]
ne = len(elems)
states = np.zeros((ns, ne))
rewards = np.zeros(ns)

for i in range(ns):
  entry = starOH2element[i]
  rewards[i] = entry["Energy"]
  for j in range(ne):
    if entry[elems[j]] == '1':
      states[i, j] = 1

In [ ]:
print(states[0:10, :])
print(rewards)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

#### Generate the set of all possible tuples (s, a, r, s')
each tuple will be of the form: 
( np.array(ne), np.array(ne), float, np.array(ne) )

In [ ]:
na = ne
def get_neighbors(current_state):
  '''
  Gets a list of possible neighbors to a given state that an agent can 
  move to. 
  This means we can swap out on element, add one element, or delete one element 
  at a time but not to exceed 3 elements and must have at least one element. 
  The condition not to exceed 3 elements will be self-enforced because we only 
  allow s1 to come from the set S (so don't need to check the condition a second time).
  arguments:
    current_state: np.array of shape (ne, 1)
  returns:
    ix_neighbor: indexes of neighbor states
    actions: list of np.array, each of shape (ne, 1)
  '''
  current_ix = np.where(np.all(states == current_state, axis=1))[0][0]
  ix_neighbors = []
  # adds
  for i in range(ne):
    add_state = current_state.copy()
    add_state[i] += 1
    if list(add_state) in states.tolist():
      ix_neighbors.append(np.where(np.all(states == add_state, axis=1))[0][0])
  # subtracts
  for i in range(ne):
    sub_state = current_state.copy()
    sub_state[i] -= 1
    if list(sub_state) in states.tolist():
      ix_neighbors.append(np.where(np.all(states == sub_state, axis=1))[0][0])
  # exchanges
  for i in range(ne):
    if current_state[i] == 1: 
      exch_state = current_state.copy()
      exch_state[i] = 0
      for j in range(ne):
        if j == i:
           continue
        exch_state2 = exch_state.copy()
        exch_state2[j] +=1 
        if list(exch_state2) in states.tolist():
          ix_neighbors.append(np.where(np.all(states == exch_state2, axis=1))[0][0])
  # print(ix_neighbors)
  actions = states[ix_neighbors, :] - current_state
  return ix_neighbors, actions


ix_neighbors, actions = get_neighbors(states[2378, :])
print("num neighbors = ", len(ix_neighbors))
print(ix_neighbors)
print(actions)

num neighbors =  80
[80, 279, 415, 496, 554, 721, 787, 903, 1102, 1203, 1301, 1400, 1435, 1508, 1538, 1597, 1644, 1997, 2045, 2071, 2116, 2182, 2211, 2244, 2273, 2287, 2300, 2318, 2328, 2337, 2354, 2361, 2368, 2374, 2377, 0, 81, 280, 416, 497, 498, 555, 578, 904, 977, 1009, 1103, 1204, 1302, 1436, 1509, 1539, 1598, 1645, 1682, 1742, 1835, 1870, 1918, 1966, 2046, 2072, 2117, 2158, 2167, 2183, 2212, 2274, 2288, 2319, 2329, 2338, 2342, 2348, 2355, 2362, 2366, 2369, 2373, 2375]
[[ 1.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  0. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0. -1.]
 [ 0.  0.  0. ...  0.  0. -1.]
 [ 0.  0.  0. ...  1.  0. -1.]]


In [ ]:
states[1, :]

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [ ]:
SARS = []
for i in range(ns):
  s = states[i, :]
  print("state number: ", i)
  ix_neighbors, actions = get_neighbors(s)
  for j in range(len(ix_neighbors)):
    tup = (s, actions[j, :], rewards[ix_neighbors[j]], states[ix_neighbors[j], :])
    SARS.append(tup)

state number:  0
state number:  1
state number:  2
state number:  3
state number:  4
state number:  5
state number:  6
state number:  7
state number:  8
state number:  9
state number:  10
state number:  11
state number:  12
state number:  13
state number:  14
state number:  15
state number:  16
state number:  17
state number:  18
state number:  19
state number:  20
state number:  21
state number:  22
state number:  23
state number:  24
state number:  25
state number:  26
state number:  27
state number:  28
state number:  29
state number:  30
state number:  31
state number:  32
state number:  33
state number:  34
state number:  35
state number:  36
state number:  37
state number:  38
state number:  39
state number:  40
state number:  41
state number:  42
state number:  43
state number:  44
state number:  45
state number:  46
state number:  47
state number:  48
state number:  49
state number:  50
state number:  51
state number:  52
state number:  53
state number:  54
state number:  55
st

In [ ]:
print(len(SARS))
print(SARS[81491])

81492
(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1.]), array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0., -1.]), -3.31, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0.]))


In [ ]:
import pickle
pickleFile = open('SARS.pkl', 'wb')
pickle.dump(SARS, pickleFile)
pickleFile.close()

In [ ]:
pickleFile = open('SARS2.pkl', 'wb')
pickle.dump(SARS, pickleFile)
pickleFile.close()

In [ ]:
pickleFile = open('SARS2.pkl', 'rb')
SARS2 = pickle.load(pickleFile)
pickleFile.close()

In [ ]:
## Test data load
SARS2 = []
with open('SARS.pkl', 'rb') as pick:
  SARS2.append(pickle.load(pick))

In [ ]:
print(len(SARS2))
(s, a, r, sp)= SARS2[0]
print(s)
print(a)
print(r)
print(sp)
print(SARS2[1])
print(SARS2[81491])


81492
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
-0.193
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
(array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.]), array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    

### Import the *OH2 adsorbate catalyst file

In [ ]:
import csv

filename = "Adsorbate_starOH2_v2.csv"
starOH2 = []

with open(filename, 'r') as data:
  for line in csv.DictReader(data):
    starOH2.append(line)

In [ ]:
print("number of catalysts in starOH2: ", len(starOH2))
print("sample of data: ", starOH2[0])
print("sample of data: ", starOH2[2549]["Formula"])    

number of catalysts in starOH2:  7959
sample of data:  {'ix': '0', 'Catalyst_ID': 'random2325461', 'MPContribs_ID': '6101e41020c7bc66345c6d12', 'Formula': 'Al60H2O', 'Bulk_Material_ID': 'mp-134', 'Bulk_Formula': 'Al', 'Adsorbate_Smiles': '*OH2', 'Adsorbate_IUPAC_Formula': 'H2 O1', 'Adsorption_Energy': '-0.053', 'h': '2', 'k': '2', 'l': '1', 'Surface_Shift': '0.05', '': ''}
sample of data:  Zn16Sn16H2Rh32O


### Install the Materials Project API

In [ ]:
!pip install mp_api
!pip install mpcontribs-client

In [ ]:
my_API_key = "QJbFSwfIYIZ64kPF6UIIaAOseF1huQaf"
from mp_api.client import MPRester

###Querying the Materials Project API

In [ ]:
def get_MP_data(materials_id_list):
  with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=materials_id_list)
  return docs

def get_MP_elements(materials_id_list):
  with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=materials_id_list, fields=["material_id", "elements"])
  return docs

'''
Example
'''
ixs = list(range(len(starOH2)))
materials_id_list = []
for ix in ixs:
  materials_id_list.append(starOH2[ix]["Bulk_Material_ID"])
print(materials_id_list)
docs = get_MP_elements(materials_id_list)
print(len(docs))
for doc in docs:
  print(doc.elements)

['mp-134', 'mp-16842', 'mp-22192', 'mp-22095', 'mp-2783', 'mp-1105935', 'mp-1395', 'mp-1102657', 'mp-11486', 'mp-972351', 'mp-17449', 'mp-10846', 'mp-1206157', 'mp-569989', 'mp-680576', 'mp-1215726', 'mp-1184684', 'mp-1183306', 'mp-1105552', 'mp-1345', 'mp-1078008', 'mp-1188336', 'mp-989407', 'mp-11870', 'mp-1601', 'mp-1220003', 'mp-1102895', 'mp-1087486', 'mp-1205321', 'mp-146', 'mp-1079908', 'mp-15698', 'mp-1224275', 'mp-1018055', 'mp-1077116', 'mp-580930', 'mp-1196650', 'mp-1206529', 'mp-12783', 'mp-11546', 'mp-1225656', 'mp-27840', 'mp-1219539', 'mp-1221843', 'mp-979911', 'mp-1218060', 'mp-1179520', 'mp-101', 'mp-823', 'mp-1186', 'mp-1025573', 'mp-637263', 'mp-1072724', 'mp-17964', 'mp-1823', 'mp-823', 'mp-1027645', 'mp-866173', 'mp-619905', 'mp-21340', 'mp-23279', 'mp-7526', 'mp-567276', 'mp-570832', 'mp-2752', 'mvc-14442', 'mp-1079260', 'mp-1215513', 'mp-11263', 'mp-1214809', 'mp-21328', 'mp-1104165', 'mp-1219512', 'mp-35152', 'mp-1006118', 'mp-568789', 'mp-1188741', 'mp-20311', 

Retrieving SummaryDoc documents:   0%|          | 0/7443 [00:00<?, ?it/s]

Streaming output truncated to the last 5000 lines.
[Element Al, Element S]
[Element Se, Element Ti]
[Element Co, Element P]
[Element Ga, Element Hf]
[Element Hf, Element Ni]
[Element Ga, Element Ni]
[Element Hf, Element W]
[Element S, Element Y, Element Zr]
[Element In, Element Pt]
[Element Cu, Element In, Element Pd]
[Element Sb, Element Si, Element Zr]
[Element Cd, Element Ga, Element Sr]
[Element Sr]
[Element S, Element Sn]
[Element Cu, Element Fe, Element S]
[Element Hf, Element S]
[Element Au, Element P]
[Element Al, Element Y, Element Zn]
[Element Na, Element P]
[Element Au, Element Sn, Element Sr]
[Element N, Element Na, Element Sn]
[Element Re, Element Si]
[Element Te, Element Y]
[Element C, Element Mo]
[Element Cr, Element Hf]
[Element Bi, Element In, Element S]
[Element Mo, Element Pd]
[Element P, Element W]
[Element Sn, Element Ti]
[Element Cr, Element Ni, Element P]
[Element Nb, Element Ru, Element Sb]
[Element H, Element Hf, Element V]
[Element Ni, Element S, Element Ti]
[

In [ ]:
print(len(docs))
print(docs[0])

7443
MPDataDoc<SummaryDoc>
elements=[Element Ir, Element P],
material_id=MPID(mp-10155)

Fields not requested:
['builder_meta', 'nsites', 'nelements', 'composition', 'composition_reduced', 'formula_pretty', 'formula_anonymous', 'chemsys', 'volume', 'density', 'density_atomic', 'symmetry', 'property_name', 'deprecated', 'deprecation_reasons', 'last_updated', 'origins', 'warnings', 'structure', 'task_ids', 'uncorrected_energy_per_atom', 'energy_per_atom', 'formation_energy_per_atom', 'energy_above_hull', 'is_stable', 'equilibrium_reaction_energy_per_atom', 'decomposes_to', 'xas', 'grain_boundaries', 'band_gap', 'cbm', 'vbm', 'efermi', 'is_gap_direct', 'is_metal', 'es_source_calc_id', 'bandstructure', 'dos', 'dos_energy_up', 'dos_energy_down', 'is_magnetic', 'ordering', 'total_magnetization', 'total_magnetization_normalized_vol', 'total_magnetization_normalized_formula_units', 'num_magnetic_sites', 'num_unique_magnetic_sites', 'types_of_magnetic_species', 'k_voigt', 'k_reuss', 'k_vrh', 'g

In [ ]:
myFile = open('id_elements.csv', 'w')
writer = csv.writer(myFile)
writer.writerow(['material_id', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])
for doc in docs:
  l = []
  l.append(doc.material_id)
  for e in doc.elements:
    l.append(e)
  writer.writerow(l)
myFile.close()

In [ ]:
for catalyst in starOH2:
  docs = get_MP_data([catalyst["Bulk_Material_ID"]])
  if len(docs) != 0:
    e = docs[0].elements
    for i in range(10):
      if i == 0:
        if i >= len(e):
          catalyst["Element_0"] = "" 
        else:
          catalyst["Element_0"] = e[i]
      if i == 1:
        if i >= len(e):
          catalyst["Element_1"] = "" 
        else:
          catalyst["Element_1"] = e[i]
      if i == 2:
        if i >= len(e):
          catalyst["Element_2"] = "" 
        else:
          catalyst["Element_2"] = e[i]
      if i == 3:
        if i >= len(e):
          catalyst["Element_3"] = "" 
        else:
          catalyst["Element_3"] = e[i]
      if i == 4:
        if i >= len(e):
          catalyst["Element_4"] = "" 
        else:
          catalyst["Element_4"] = e[i]
      if i == 5:
        if i >= len(e):
          catalyst["Element_5"] = "" 
        else:
          catalyst["Element_5"] = e[i]
      if i == 6:
        if i >= len(e):
          catalyst["Element_6"] = "" 
        else:
          catalyst["Element_6"] = e[i]
      if i == 7:
        if i >= len(e):
          catalyst["Element_7"] = "" 
        else:
          catalyst["Element_7"] = e[i]
      if i == 8:
        if i >= len(e):
          catalyst["Element_8"] = "" 
        else:
          catalyst["Element_8"] = e[i]
      if i == 9:
        if i >= len(e):
          catalyst["Element_9"] = "" 
        else:
          catalyst["Element_9"] = e[i]
    print("index ", catalyst["ix"], ", catalyst: ", catalyst)


In [ ]:
e = docs[0].elements
print(e)
print(len(e))
for i in range(len(e)):
  print(e[i])

[Element P, Element Rh, Element Zr]
3
P
Rh
Zr


In [ ]:
print(starOH2[0])

{'ix': '0', 'Catalyst_ID': 'random2325461', 'MPContribs_ID': '6101e41020c7bc66345c6d12', 'Formula': 'Al60H2O', 'Bulk_Material_ID': 'mp-134', 'Bulk_Formula': 'Al', 'Adsorbate_Smiles': '*OH2', 'Adsorbate_IUPAC_Formula': 'H2 O1', 'Adsorption_Energy': '-0.053', 'h': '2', 'k': '2', 'l': '1', 'Surface_Shift': '0.05', '': '', 'Element_0': Element Al}


## Other testing -- can ignore for now

In [ ]:
with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=["mp-149", "mp-13", "mp-22526", "mp-146"])

/usr/local/lib/python3.10/dist-packages/mp_api/client/mprester.py:182: UserWarning: mpcontribs-client not installed. Install the package to query MPContribs data, or construct pourbaix diagrams: 'pip install mpcontribs-client'
  warnings.warn(


Retrieving SummaryDoc documents:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
print(len(docs))
print("docs[0]: ", docs[0])
print("dosc[1]: ", docs[1])
print("dosc[2]: ", docs[2])
print("dosc[3]: ", docs[3])

4
docs[0]:  MPDataDoc<SummaryDoc>
builder_meta=EmmetMeta(emmet_version='0.38.6', pymatgen_version='2022.10.22', pull_request=825, database_version='2022.10.28', build_date=datetime.datetime(2022, 10, 28, 0, 56, 26, 531000)),
nsites=1,
elements=[Element V],
nelements=1,
composition=Comp: V1,
composition_reduced=Comp: V1,
formula_pretty='V',
formula_anonymous='A',
chemsys='V',
volume=13.263780153478194,
density=6.37754470312308,
density_atomic=13.263780153478194,
symmetry=SymmetryData(crystal_system=<CrystalSystem.cubic: 'Cubic'>, symbol='Im-3m', number=229, point_group='m-3m', symprec=0.1, version='1.16.2'),
property_name='summary',
material_id=MPID(mp-146),
deprecated=False,
deprecation_reasons=None,
last_updated=datetime.datetime(2022, 10, 28, 0, 56, 26, 531000),
origins=[],
warnings=[],
structure=Structure Summary
Lattice
    abc : 2.5828336109207948 2.5828334497508623 2.58283362
 angles : 109.47122996959392 109.47122870554041 109.47121382749214
 volume : 13.263780153478194
      A :

In [ ]:
list_of_available_fields = mpr.summary.available_fields
print(list_of_available_fields)

['builder_meta', 'nsites', 'elements', 'nelements', 'composition', 'composition_reduced', 'formula_pretty', 'formula_anonymous', 'chemsys', 'volume', 'density', 'density_atomic', 'symmetry', 'property_name', 'material_id', 'deprecated', 'deprecation_reasons', 'last_updated', 'origins', 'warnings', 'structure', 'task_ids', 'uncorrected_energy_per_atom', 'energy_per_atom', 'formation_energy_per_atom', 'energy_above_hull', 'is_stable', 'equilibrium_reaction_energy_per_atom', 'decomposes_to', 'xas', 'grain_boundaries', 'band_gap', 'cbm', 'vbm', 'efermi', 'is_gap_direct', 'is_metal', 'es_source_calc_id', 'bandstructure', 'dos', 'dos_energy_up', 'dos_energy_down', 'is_magnetic', 'ordering', 'total_magnetization', 'total_magnetization_normalized_vol', 'total_magnetization_normalized_formula_units', 'num_magnetic_sites', 'num_unique_magnetic_sites', 'types_of_magnetic_species', 'k_voigt', 'k_reuss', 'k_vrh', 'g_voigt', 'g_reuss', 'g_vrh', 'universal_anisotropy', 'homogeneous_poisson', 'e_total

### Querying Catalysis Explorer for *CHO here:
https://next-gen.materialsproject.org/catalysis?_limit=10&data__adsorbateSmiles__exact=%2ACHO

"Search catalysis data from the Open Catalyst 2020 (OC20) Dataset."

In [ ]:
with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=[
        "mp-1214123",
        "mp-1193800", 
        "mp-1102559", 
        "mp-1215496", 
        "mp-1018713",
        "mp-1023933",
        "mp-865533",
        "mp-1224459",
        "mp-1227660",
        "mp-1017541",
        ])
nDocs = len(docs)
print("Number of retrieved catalysts: ", nDocs)
for i in range (nDocs):
  print("docs[", i, "]: ", docs[0])

Retrieving SummaryDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

Number of retrieved catalysts:  10
docs[ 0 ]:  MPDataDoc<SummaryDoc>
builder_meta=EmmetMeta(emmet_version='0.38.6', pymatgen_version='2022.10.22', pull_request=825, database_version='2022.10.28', build_date=datetime.datetime(2022, 10, 28, 0, 56, 1, 797000)),
nsites=17,
elements=[Element Ca, Element Os, Element Sb],
nelements=3,
composition=Comp: Ca1 Sb12 Os4,
composition_reduced=Comp: Ca1 Sb12 Os4,
formula_pretty='Ca(Sb3Os)4',
formula_anonymous='AB4C12',
chemsys='Ca-Os-Sb',
volume=420.5651319734559,
density=8.931637519812604,
density_atomic=24.739125410203286,
symmetry=SymmetryData(crystal_system=<CrystalSystem.cubic: 'Cubic'>, symbol='Im-3', number=204, point_group='m-3', symprec=0.1, version='1.16.2'),
property_name='summary',
material_id=MPID(mp-1214123),
deprecated=False,
deprecation_reasons=None,
last_updated=datetime.datetime(2022, 10, 28, 0, 56, 1, 797000),
origins=[],
warnings=[],
structure=Structure Summary
Lattice
    abc : 8.174948990020853 8.174948990020853 8.17494899002085