###Mount Google Drive

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
%cd '/content/gdrive/MyDrive/CS224R/Project/MaterialsProject/'
!pwd
!ls -al

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-84-93e116c259ed>", line 1, in <cell line: 1>
    get_ipython().run_line_magic('cd', "'/content/gdrive/MyDrive/CS224R/Project/MaterialsProject/'")
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2418, in run_line_magic
    result = fn(*args, **kwargs)
  File "<decorator-gen-85>", line 2, in cd
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py", line 342, in cd
    oldcwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-84-93e116c259ed>", line 1, in <cell line: 1>
    get_ipython().run_line_magic('cd', "'/content/gdrive/MyDrive/CS224R/Project/MaterialsProject/'")
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2418, in run_line_magic
    result = fn(*args, **kwargs)
  File "<decorator-gen-85>", line 2, in cd
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py", line 342, in cd
    oldcwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-84-93e116c259ed>", line 1, in <cell line: 1>
    get_ipython().run_line_magic('cd', "'/content/gdrive/MyDrive/CS224R/Project/MaterialsProject/'")
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2418, in run_line_magic
    result = fn(*args, **kwargs)
  File "<decorator-gen-85>", line 2, in cd
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py", line 342, in cd
    oldcwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10

### Generating Sample Trajectories

In [ ]:
## Test data load
import pickle
import random
import numpy as np

pickleFile = open('SARS2.pkl', 'rb')
SARS2 = pickle.load(pickleFile)
pickleFile.close()

print(len(SARS2))
(s, a, r, sp)= SARS2[0]
print(s)
print(a)
print(r)
print(sp)
print(SARS2[1])
print(SARS2[81491])
print(type(SARS2))

obs_dim = 55
ob_min_energy = np.zeros(obs_dim)
ix_Si = 42
ix_C = 6
ob_min_energy[ix_Si] = 1
ob_min_energy[ix_C] = 1
print(ob_min_energy)

81492
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
-0.193
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
(array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.]), array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    

In [ ]:
def sample_trajectory(SARSlist, max_path_length, ob_terminal):
  '''
  args:
    SARSlist: list of possible (ob, ac, rew, next_ob) combinations, where:
      ob: 1-D np.array of length obs_dim
      ac: 1-D np.array of length acs_dim
      rew: float 
      next_ob: 1-D np.array of length obs_dim
    max_path_length: int max length of path
    ob_terminal: the terminal state (typically the min energy state in observations)

  returns:
    Path object 
  '''
  SARSlist_len = len(SARSlist)
  obs, acs, rewards, next_obs, terminals, image_obs = [], [], [], [], [], []
  steps = 0

  k0 = np.random.choice(SARSlist_len)
  (ob, ac, rew, next_ob) = SARSlist[k0]
  while True:
    obs.append(ob)
    acs.append(ac)
    next_obs.append(next_ob)
    rewards.append(rew)
    done = np.array_equal(next_ob, ob_terminal)
    steps += 1

    # If the episode ended, the corresponding terminal value is 1
    # otherwise, it is 0
    if done or steps > max_path_length:
        terminals.append(1)
        break
    else:
        terminals.append(0)

    # If not ended, sample at random a transition starting from the next observation
    possible_next_SARS = [sars for sars in SARSlist if np.array_equal(sars[0], next_ob)]
    (ob, ac, rew, next_ob) = random.choice(possible_next_SARS)

  return Path(obs, [], acs, rewards, next_obs, terminals)


def sample_trajectories(SARSlist, max_path_length, ob_terminal, min_timesteps_per_batch):

    timesteps_this_batch = 0
    paths = []
    while timesteps_this_batch < min_timesteps_per_batch:

        #collect rollout
        path = sample_trajectory(SARSlist, max_path_length, ob_terminal)
        paths.append(path)

        #count steps
        timesteps_this_batch += get_pathlength(path)
        print('At timestep:    ', timesteps_this_batch, '/', min_timesteps_per_batch, end='\r')

    return paths, timesteps_this_batch


def sample_n_trajectories(SARSlist, max_path_length, ob_terminal, ntraj):

    paths = []
    for i in range(ntraj):
        # collect rollout
        path = sample_trajectory(SARSlist, max_path_length, ob_terminal)
        paths.append(path)

    return paths


def Path(obs, image_obs, acs, rewards, next_obs, terminals):
    """
        Take info (separate arrays) from a single rollout
        and return it in a single dictionary
    """
    if image_obs != []:
        image_obs = np.stack(image_obs, axis=0)
    return {"observation" : np.array(obs, dtype=np.float32),
            "image_obs" : np.array(image_obs, dtype=np.uint8),
            "reward" : np.array(rewards, dtype=np.float32),
            "action" : np.array(acs, dtype=np.float32),
            "next_observation": np.array(next_obs, dtype=np.float32),
            "terminal": np.array(terminals, dtype=np.float32)}


In [ ]:
p = sample_trajectory(SARS2, 5, ob_min_energy)

In [ ]:
p["terminal"]

array([0., 0., 0., 0., 0., 1.], dtype=float32)

In [ ]:
p["next_observation"][-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.], dtype=float32)

#### Process the unique element catalyst file

In [ ]:
import csv
import numpy as np

filename = "starCH2.csv"
starOH2element = []

with open(filename, 'r') as data:
  for line in csv.DictReader(data):
    starOH2element.append(line)

In [ ]:
print("number of catalysts in starOHelement: ", len(starOH2element))
print("sample of data: ", starOH2element[0])
print("sample of data: ", starOH2element[2109]["Bulk_Formula"])    

number of catalysts in starOHelement:  2759
sample of data:  {'\ufeffix': '1', 'Element combo': 'Ag', 'material_id': 'mp-989737', 'El0': 'Ag', 'El1': '', 'El2': '', 'Bulk_Formula': 'Ag', 'Energy': '0.172', 'Ag': '1', 'Al': '0', 'As': '0', 'Au': '0', 'B': '0', 'Bi': '0', 'C': '0', 'Ca': '0', 'Cd': '0', 'Cl': '0', 'Co': '0', 'Cr': '0', 'Cs': '0', 'Cu': '0', 'Fe': '0', 'Ga': '0', 'Ge': '0', 'H': '0', 'Hf': '0', 'Hg': '0', 'In': '0', 'Ir': '0', 'K': '0', 'Mn': '0', 'Mo': '0', 'N': '0', 'Na': '0', 'Nb': '0', 'Ni': '0', 'Os': '0', 'P': '0', 'Pb': '0', 'Pd': '0', 'Pt': '0', 'Rb': '0', 'Re': '0', 'Rh': '0', 'Ru': '0', 'S': '0', 'Sb': '0', 'Sc': '0', 'Se': '0', 'Si': '0', 'Sn': '0', 'Sr': '0', 'Ta': '0', 'Tc': '0', 'Te': '0', 'Ti': '0', 'Tl': '0', 'V': '0', 'W': '0', 'Y': '0', 'Zn': '0', 'Zr': '0'}
sample of data:  TiCoGe


#### Create the numpy matrix of states

In [ ]:
ns = len(starOH2element)
elems = [
    'Ag', 'Al',	'As', 'Au', 'B', 'Bi', 'C', 'Ca', 'Cd', 'Cl', 'Co', 'Cr', 'Cs', 'Cu', 'Fe', 'Ga', 'Ge', 'H', 'Hf', 'Hg', 'In', 'Ir', 'K', 'Mn', 'Mo', 'N', 'Na', 'Nb', 'Ni', 'Os', 'P', 'Pb', 'Pd', 'Pt', 'Rb', 'Re', 'Rh', 'Ru', 'S', 'Sb', 'Sc', 'Se', 'Si', 'Sn', 'Sr', 'Ta', 'Tc', 'Te', 'Ti', 'Tl', 'V', 'W', 'Y', 'Zn', 'Zr'
    ]
ne = len(elems)
states = np.zeros((ns, ne))
rewards = np.zeros(ns)

for i in range(ns):
  entry = starOH2element[i]
  rewards[i] = entry["Energy"]
  for j in range(ne):
    if entry[elems[j]] == '1':
      states[i, j] = 1

In [ ]:
print(states[0:10, :])
print(rewards)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0

#### Generate the set of all possible tuples (s, a, r, s')
each tuple will be of the form: 
( np.array(ne), np.array(ne), float, np.array(ne) )

In [ ]:
na = ne
def get_neighbors(current_state):
  '''
  Gets a list of possible neighbors to a given state that an agent can 
  move to. 
  This means we can swap out on element, add one element, or delete one element 
  at a time but not to exceed 3 elements and must have at least one element. 
  The condition not to exceed 3 elements will be self-enforced because we only 
  allow s1 to come from the set S (so don't need to check the condition a second time).
  arguments:
    current_state: np.array of shape (ne, 1)
  returns:
    ix_neighbor: indexes of neighbor states
    actions: list of np.array, each of shape (ne, 1)
  '''
  current_ix = np.where(np.all(states == current_state, axis=1))[0][0]
  ix_neighbors = []
  # adds
  for i in range(ne):
    add_state = current_state.copy()
    add_state[i] += 1
    if list(add_state) in states.tolist():
      ix_neighbors.append(np.where(np.all(states == add_state, axis=1))[0][0])
  # subtracts
  for i in range(ne):
    sub_state = current_state.copy()
    sub_state[i] -= 1
    if list(sub_state) in states.tolist():
      ix_neighbors.append(np.where(np.all(states == sub_state, axis=1))[0][0])
  # exchanges
  for i in range(ne):
    if current_state[i] == 1: 
      exch_state = current_state.copy()
      exch_state[i] = 0
      for j in range(ne):
        if j == i:
           continue
        exch_state2 = exch_state.copy()
        exch_state2[j] +=1 
        if list(exch_state2) in states.tolist():
          ix_neighbors.append(np.where(np.all(states == exch_state2, axis=1))[0][0])
  # print(ix_neighbors)
  actions = states[ix_neighbors, :] - current_state
  return ix_neighbors, actions


ix_neighbors, actions = get_neighbors(states[2109, :])
print("num neighbors = ", len(ix_neighbors))
print(ix_neighbors)
print(actions)

num neighbors =  31
[2146, 2108, 406, 2091, 2125, 2133, 2166, 2182, 2187, 2147, 2148, 2149, 2150, 2508, 2087, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 190, 444, 634, 706, 1046, 410, 1613, 2375]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [ ]:
states[1, :]

array([1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0.])

In [ ]:
SARS = []
for i in range(ns):
  s = states[i, :]
  print("state number: ", i)
  ix_neighbors, actions = get_neighbors(s)
  for j in range(len(ix_neighbors)):
    tup = (s, actions[j, :], rewards[ix_neighbors[j]], states[ix_neighbors[j], :])
    SARS.append(tup)

state number:  0
state number:  1
state number:  2
state number:  3
state number:  4
state number:  5
state number:  6
state number:  7
state number:  8
state number:  9
state number:  10
state number:  11
state number:  12
state number:  13
state number:  14
state number:  15
state number:  16
state number:  17
state number:  18
state number:  19
state number:  20
state number:  21
state number:  22
state number:  23
state number:  24
state number:  25
state number:  26
state number:  27
state number:  28
state number:  29
state number:  30
state number:  31
state number:  32
state number:  33
state number:  34
state number:  35
state number:  36
state number:  37
state number:  38
state number:  39
state number:  40
state number:  41
state number:  42
state number:  43
state number:  44
state number:  45
state number:  46
state number:  47
state number:  48
state number:  49
state number:  50
state number:  51
state number:  52
state number:  53
state number:  54
state number:  55
st

In [ ]:
import pickle
pickleFile = open('starCH2_SARS.pkl', 'wb')
pickle.dump(SARS, pickleFile)
pickleFile.close()

In [ ]:
print(len(SARS))
print(SARS[96866])
%ls

96867
(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1.]), array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0., -1.]), 0.138, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0.]))
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
ls: cannot open directory '.': Transport endpoin

In [ ]:
import os
path = '/content/gdrive/MyDrive/CS224R/Project/MaterialsProject/'
os.chdir(path)
%ls

Adsorbate_starOH2_v2.csv          starCH4_SARS.pkl
get_materials_project_data.ipynb  starN2.csv
id_elements.csv                   starN2_SARS.pkl
Load_Pickel.ipynb                 starNH3.csv
SARS2.pkl                         starNH3_SARS.pkl
starCH2.csv                       starOH2_lowest_energy5-20-23.gsheet
starCH2.gsheet                    starOH2_lowest_energy5-20-23v2.csv
starCH4.csv                       starOH_SARS.pkl


In [ ]:
import pickle
pickleFile = open('starCH2_SARS.pkl', 'wb')
pickle.dump(SARS, pickleFile)
pickleFile.close()

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-87-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-87-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/dist-packages/mpcontribs/client/__init__.py", line 283, in _hide_traceback
    etype, value, _ipython.InteractiveTB(etype, value, tb)
  File "/usr/l

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-87-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/dist-packages/mpcontribs/client/__init__.py", line 283, in _hide_traceback
    etype, value, _ipython.InteractiveTB(etype, value, tb)
  File "/usr/l

In [ ]:
import pickle
pickleFile = open('starCH2_SARS.pkl', 'wb')
pickle.dump(SARS, pickleFile)
pickleFile.close()

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-81-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-81-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/dist-packages/mpcontribs/client/__init__.py", line 283, in _hide_traceback
    etype, value, _ipython.InteractiveTB(etype, value, tb)
  File "/usr/l

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-81-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/dist-packages/mpcontribs/client/__init__.py", line 283, in _hide_traceback
    etype, value, _ipython.InteractiveTB(etype, value, tb)
  File "/usr/l

In [ ]:
pickleFile = open('SARS2.pkl', 'wb')
pickle.dump(SARS, pickleFile)
pickleFile.close()

In [ ]:
## Test data load
import pickle

pickleFile = open('starCH2_SARS.pkl', 'rb')
SARS2 = pickle.load(pickleFile)
pickleFile.close()

In [ ]:
## Test data load
import pickle
SARS2 = []
with open('SARS.pkl', 'rb') as pick:
  SARS2.append(pickle.load(pick))

In [ ]:
print(len(SARS2))
(s, a, r, sp)= SARS2[0]
print(s)
print(a)
print(r)
print(sp)
print(SARS2[1])
print(SARS2[68061])


96867
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
-1.176
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
(array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.]), array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    

### Import the *OH2 adsorbate catalyst file

In [ ]:
import csv

filename = "starCH4.csv"
starOH2 = []

with open(filename, 'r') as data:
  for line in csv.DictReader(data):
    starOH2.append(line)

In [ ]:
print("number of catalysts in starOH2: ", len(starOH2))
print("sample of data: ", starOH2[0])
print("sample of data: ", starOH2[2456]["Element combo"])    

number of catalysts in starOH2:  2457
sample of data:  {'ix': '1', 'Element combo': 'Ag', 'material_id': 'mp-124'}
sample of data:  ZrZnRh


### Install the Materials Project API

In [ ]:
!pip install mp_api
!pip install mpcontribs-client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 115.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.4/152.4 kB 23.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.4/561.4 kB 58.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.3/515.3 kB 55.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.1/112.1 kB 17.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.4/98.4 kB 16.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.6/485.6 kB 53.9 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 7.3 MB/s eta 0:

In [ ]:
my_API_key = "QJbFSwfIYIZ64kPF6UIIaAOseF1huQaf"
from mp_api.client import MPRester

###Querying the Materials Project API

In [ ]:
def get_MP_data(materials_id_list):
  with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=materials_id_list)
  return docs

def get_MP_elements(materials_id_list):
  with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=materials_id_list, fields=["material_id", "elements"])
  return docs

'''
Example
'''
ixs = list(range(len(starOH2)))
materials_id_list = []
for ix in ixs:
  materials_id_list.append(starOH2[ix]["material_id"])
print(materials_id_list)
docs = get_MP_elements(materials_id_list)
print(len(docs))
for doc in docs:
  print(doc.elements)

['mp-124', 'mp-1103642', 'mp-1229158', 'mp-1183214', 'mp-1183166', 'mp-23474', 'mp-33618', 'mp-570687', 'mp-1096802', 'mp-27821', 'mp-1183222', 'mp-1078079', 'mp-1025385', 'mp-5470', 'mp-1183209', 'mp-32868', 'mp-1205392', 'mp-1229000', 'mp-568971', 'mp-611', 'mp-29849', 'mp-1229005', 'mp-1229118', 'mp-1229011', 'mp-684798', 'mp-134', 'mvc-11819', 'mvc-16083', 'mp-1228988', 'mp-2172', 'mp-1025306', 'mp-1018179', 'mp-1591', 'mp-7909', 'mp-25469', 'mp-5496', 'mp-1228607', 'mp-984352', 'mp-862695', 'mp-867780', 'mp-991900', 'mp-862781', 'mp-675628', 'mp-1214842', 'mp-985806', 'mp-23434', 'mp-1228938', 'mp-866296', 'mp-12550', 'mp-1183191', 'mvc-16090', 'mp-862691', 'mp-4689', 'mp-867330', 'mp-29111', 'mp-1228893', 'mp-1228953', 'mp-1228918', 'mp-1228888', 'mp-1228900', 'mp-867904', 'mp-1228562', 'mp-1183246', 'mp-2294', 'mp-866284', 'mp-550', 'mp-18093', 'mp-661', 'mp-1229048', 'mp-1194643', 'mp-1183155', 'mp-1228426', 'mp-567929', 'mp-1550', 'mp-16522', 'mp-862715', 'mp-1228856', 'mp-110

Retrieving SummaryDoc documents:   0%|          | 0/2409 [00:00<?, ?it/s]

2409
[Element Mn, Element Sb, Element Tc]
[Element Mn, Element Rh, Element Tl]
[Element As, Element Mn, Element V]
[Element Mn, Element Pt, Element Zn]
[Element Mn, Element S, Element Zn]
[Element Mn, Element Te, Element Zn]
[Element Mo, Element S, Element Se]
[Element Mo, Element S, Element W]
[Element As, Element Mo, Element P]
[Element Ir, Element Mo]
[Element Mo, Element P]
[Element Mo, Element Pd]
[Element Mo, Element P, Element Rh]
[Element Mo, Element Rh]
[Element Mo, Element S, Element Se]
[Element Mo, Element S, Element W]
[Element Mo, Element Se, Element W]
[Element Na]
[Element Mo, Element Na, Element Se]
[Element Na, Element Nb, Element S]
[Element Na, Element S, Element V]
[Element Na, Element Se, Element V]
[Element Ag, Element Na]
[Element Au, Element Bi, Element Na]
[Element Cd, Element Na]
[Element As, Element Cd, Element Na]
[Element Co, Element Na, Element Se]
[Element As, Element Ga, Element Na]
[Element Hg, Element Na]
[Element N, Element Na]
[Element Na, Element P

In [ ]:
print(len(docs))
print(docs[0])

2409
MPDataDoc<SummaryDoc>
elements=[Element Mn, Element Sb, Element Tc],
material_id=MPID(mp-1186002)

Fields not requested:
['builder_meta', 'nsites', 'nelements', 'composition', 'composition_reduced', 'formula_pretty', 'formula_anonymous', 'chemsys', 'volume', 'density', 'density_atomic', 'symmetry', 'property_name', 'deprecated', 'deprecation_reasons', 'last_updated', 'origins', 'warnings', 'structure', 'task_ids', 'uncorrected_energy_per_atom', 'energy_per_atom', 'formation_energy_per_atom', 'energy_above_hull', 'is_stable', 'equilibrium_reaction_energy_per_atom', 'decomposes_to', 'xas', 'grain_boundaries', 'band_gap', 'cbm', 'vbm', 'efermi', 'is_gap_direct', 'is_metal', 'es_source_calc_id', 'bandstructure', 'dos', 'dos_energy_up', 'dos_energy_down', 'is_magnetic', 'ordering', 'total_magnetization', 'total_magnetization_normalized_vol', 'total_magnetization_normalized_formula_units', 'num_magnetic_sites', 'num_unique_magnetic_sites', 'types_of_magnetic_species', 'k_voigt', 'k_reus

In [ ]:
myFile = open('id_elements.csv', 'w')
writer = csv.writer(myFile)
writer.writerow(['material_id', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])
for doc in docs:
  l = []
  l.append(doc.material_id)
  for e in doc.elements:
    l.append(e)
  writer.writerow(l)
myFile.close()

In [ ]:
print(starOH2[0])

{'ix': '0', 'Catalyst_ID': 'random2325461', 'MPContribs_ID': '6101e41020c7bc66345c6d12', 'Formula': 'Al60H2O', 'Bulk_Material_ID': 'mp-134', 'Bulk_Formula': 'Al', 'Adsorbate_Smiles': '*OH2', 'Adsorbate_IUPAC_Formula': 'H2 O1', 'Adsorption_Energy': '-0.053', 'h': '2', 'k': '2', 'l': '1', 'Surface_Shift': '0.05', '': '', 'Element_0': Element Al}


In [ ]:
import pickle
pickleFile = open('starCH2_SARS.pkl', 'wb')
pickle.dump(SARS, pickleFile)
pickleFile.close()

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-85-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-85-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/dist-packages/mpcontribs/client/__init__.py", line 283, in _hide_traceback
    etype, value, _ipython.InteractiveTB(etype, value, tb)
  File "/usr/l

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-85-f2466a128b88>", line 2, in <cell line: 2>
    pickleFile = open('starCH2_SARS.pkl', 'wb')
OSError: [Errno 107] Transport endpoint is not connected: 'starCH2_SARS.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/dist-packages/mpcontribs/client/__init__.py", line 283, in _hide_traceback
    etype, value, _ipython.InteractiveTB(etype, value, tb)
  File "/usr/l

## Other testing -- can ignore for now

In [ ]:
with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=["mp-149", "mp-13", "mp-22526", "mp-146"])

/usr/local/lib/python3.10/dist-packages/mp_api/client/mprester.py:182: UserWarning: mpcontribs-client not installed. Install the package to query MPContribs data, or construct pourbaix diagrams: 'pip install mpcontribs-client'
  warnings.warn(


Retrieving SummaryDoc documents:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
print(len(docs))
print("docs[0]: ", docs[0])
print("dosc[1]: ", docs[1])
print("dosc[2]: ", docs[2])
print("dosc[3]: ", docs[3])

4
docs[0]:  MPDataDoc<SummaryDoc>
builder_meta=EmmetMeta(emmet_version='0.38.6', pymatgen_version='2022.10.22', pull_request=825, database_version='2022.10.28', build_date=datetime.datetime(2022, 10, 28, 0, 56, 26, 531000)),
nsites=1,
elements=[Element V],
nelements=1,
composition=Comp: V1,
composition_reduced=Comp: V1,
formula_pretty='V',
formula_anonymous='A',
chemsys='V',
volume=13.263780153478194,
density=6.37754470312308,
density_atomic=13.263780153478194,
symmetry=SymmetryData(crystal_system=<CrystalSystem.cubic: 'Cubic'>, symbol='Im-3m', number=229, point_group='m-3m', symprec=0.1, version='1.16.2'),
property_name='summary',
material_id=MPID(mp-146),
deprecated=False,
deprecation_reasons=None,
last_updated=datetime.datetime(2022, 10, 28, 0, 56, 26, 531000),
origins=[],
warnings=[],
structure=Structure Summary
Lattice
    abc : 2.5828336109207948 2.5828334497508623 2.58283362
 angles : 109.47122996959392 109.47122870554041 109.47121382749214
 volume : 13.263780153478194
      A :

In [ ]:
list_of_available_fields = mpr.summary.available_fields
print(list_of_available_fields)

['builder_meta', 'nsites', 'elements', 'nelements', 'composition', 'composition_reduced', 'formula_pretty', 'formula_anonymous', 'chemsys', 'volume', 'density', 'density_atomic', 'symmetry', 'property_name', 'material_id', 'deprecated', 'deprecation_reasons', 'last_updated', 'origins', 'warnings', 'structure', 'task_ids', 'uncorrected_energy_per_atom', 'energy_per_atom', 'formation_energy_per_atom', 'energy_above_hull', 'is_stable', 'equilibrium_reaction_energy_per_atom', 'decomposes_to', 'xas', 'grain_boundaries', 'band_gap', 'cbm', 'vbm', 'efermi', 'is_gap_direct', 'is_metal', 'es_source_calc_id', 'bandstructure', 'dos', 'dos_energy_up', 'dos_energy_down', 'is_magnetic', 'ordering', 'total_magnetization', 'total_magnetization_normalized_vol', 'total_magnetization_normalized_formula_units', 'num_magnetic_sites', 'num_unique_magnetic_sites', 'types_of_magnetic_species', 'k_voigt', 'k_reuss', 'k_vrh', 'g_voigt', 'g_reuss', 'g_vrh', 'universal_anisotropy', 'homogeneous_poisson', 'e_total

### Querying Catalysis Explorer for *CHO here:
https://next-gen.materialsproject.org/catalysis?_limit=10&data__adsorbateSmiles__exact=%2ACHO

"Search catalysis data from the Open Catalyst 2020 (OC20) Dataset."

In [ ]:
with MPRester(my_API_key) as mpr:
    docs = mpr.summary.search(material_ids=[
        "mp-1214123",
        "mp-1193800", 
        "mp-1102559", 
        "mp-1215496", 
        "mp-1018713",
        "mp-1023933",
        "mp-865533",
        "mp-1224459",
        "mp-1227660",
        "mp-1017541",
        ])
nDocs = len(docs)
print("Number of retrieved catalysts: ", nDocs)
for i in range (nDocs):
  print("docs[", i, "]: ", docs[0])

Retrieving SummaryDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

Number of retrieved catalysts:  10
docs[ 0 ]:  MPDataDoc<SummaryDoc>
builder_meta=EmmetMeta(emmet_version='0.38.6', pymatgen_version='2022.10.22', pull_request=825, database_version='2022.10.28', build_date=datetime.datetime(2022, 10, 28, 0, 56, 1, 797000)),
nsites=17,
elements=[Element Ca, Element Os, Element Sb],
nelements=3,
composition=Comp: Ca1 Sb12 Os4,
composition_reduced=Comp: Ca1 Sb12 Os4,
formula_pretty='Ca(Sb3Os)4',
formula_anonymous='AB4C12',
chemsys='Ca-Os-Sb',
volume=420.5651319734559,
density=8.931637519812604,
density_atomic=24.739125410203286,
symmetry=SymmetryData(crystal_system=<CrystalSystem.cubic: 'Cubic'>, symbol='Im-3', number=204, point_group='m-3', symprec=0.1, version='1.16.2'),
property_name='summary',
material_id=MPID(mp-1214123),
deprecated=False,
deprecation_reasons=None,
last_updated=datetime.datetime(2022, 10, 28, 0, 56, 1, 797000),
origins=[],
warnings=[],
structure=Structure Summary
Lattice
    abc : 8.174948990020853 8.174948990020853 8.17494899002085

In [ ]:
for catalyst in starOH2:
  docs = get_MP_data([catalyst["material_id"]])
  if len(docs) != 0:
    e = docs[0].elements
    for i in range(10):
      if i == 0:
        if i >= len(e):
          catalyst["Element_0"] = "" 
        else:
          catalyst["Element_0"] = e[i]
      if i == 1:
        if i >= len(e):
          catalyst["Element_1"] = "" 
        else:
          catalyst["Element_1"] = e[i]
      if i == 2:
        if i >= len(e):
          catalyst["Element_2"] = "" 
        else:
          catalyst["Element_2"] = e[i]
      if i == 3:
        if i >= len(e):
          catalyst["Element_3"] = "" 
        else:
          catalyst["Element_3"] = e[i]
      if i == 4:
        if i >= len(e):
          catalyst["Element_4"] = "" 
        else:
          catalyst["Element_4"] = e[i]
      if i == 5:
        if i >= len(e):
          catalyst["Element_5"] = "" 
        else:
          catalyst["Element_5"] = e[i]
      if i == 6:
        if i >= len(e):
          catalyst["Element_6"] = "" 
        else:
          catalyst["Element_6"] = e[i]
      if i == 7:
        if i >= len(e):
          catalyst["Element_7"] = "" 
        else:
          catalyst["Element_7"] = e[i]
      if i == 8:
        if i >= len(e):
          catalyst["Element_8"] = "" 
        else:
          catalyst["Element_8"] = e[i]
      if i == 9:
        if i >= len(e):
          catalyst["Element_9"] = "" 
        else:
          catalyst["Element_9"] = e[i]
    print("index ", catalyst["ix"], ", catalyst: ", catalyst)


In [ ]:
e = docs[0].elements
print(e)
print(len(e))
for i in range(len(e)):
  print(e[i])

[Element P, Element Rh, Element Zr]
3
P
Rh
Zr
